(ns es.store
  "Append-only event store backed by Postgres.

   ┌──────────────────────────────────────────────────────────────────┐
   │  EVENT STREAM — the ordered sequence of events sharing a        │
   │  stream-id. Each bank account gets its own stream, e.g.         │
   │  stream-id = \"account-42\". The stream is the unit of          │
   │  consistency: optimistic concurrency and advisory locks          │
   │  operate per-stream.                                            │
   └──────────────────────────────────────────────────────────────────┘

   Identity & ordering
   ───────────────────
   • id (UUIDv7)          — globally unique event identity, time-ordered,
                            generated by the application (no DB coordination).
   • global_sequence      — monotonic DB-assigned position across ALL streams.
                            Used by projections as a catch-up cursor.
   • stream_sequence      — per-stream version counter. Used for optimistic
                            concurrency within a single aggregate.
   • event_version        — schema version for event payload shape (domain-level
                            upcasters/validators consume this).

   Concurrency strategy
   ────────────────────
   1. pg_advisory_xact_lock(md5-derived 64-bit key from stream-id)
      — serialises writes to the same stream within the DB.
   2. Version check: expected-version must equal current max(stream_sequence).
      — the 'optimistic' part: readers don't take locks; writers
        detect stale reads at commit time.
   3. UNIQUE(stream_id, stream_sequence) — safety-net constraint.

   Idempotency
   ───────────
   Command idempotency is handled by a dedicated idempotency_keys
   table (global uniqueness on idempotency_key), not by the events
  table. This avoids cross-stream races and keeps event rows focused
  on domain facts."
  (:require [next.jdbc :as jdbc]
            [next.jdbc.result-set :as rs]
            [clojure.data.json :as json]
            [es.schema :as schema]
            [malli.core :as m])
  (:import [org.postgresql.util PGobject]
           [java.sql Timestamp]
           [java.security SecureRandom]
           [java.util UUID]))

;; ——— UUIDv7 ———

(def ^:private ^SecureRandom secure-random (SecureRandom.))

(defn uuid-v7
  "Generates a UUIDv7 — a time-ordered, globally unique identifier.
   Layout (128 bits):
     48 bits  unix timestamp ms
      4 bits  version (0111 = 7)
     12 bits  random
      2 bits  variant (10)
     62 bits  random"
  []
  (let [ts     (System/currentTimeMillis)
        rand-a (bit-and (.nextInt secure-random) 0xFFF)
        rand-b (.nextLong secure-random)
        msb    (-> (bit-shift-left ts 16)
                   (bit-or (bit-shift-left 7 12))
                   (bit-or rand-a))
        lsb    (-> (bit-and rand-b 0x3FFFFFFFFFFFFFFF)
                   (bit-or (unchecked-long 0x8000000000000000)))]
    (UUID. msb lsb)))

;; ——— JSONB helpers ———

(defn ->pgobject
  "Clojure value → Postgres JSONB PGobject."
  [m]
  (doto (PGobject.)
    (.setType "jsonb")
    (.setValue (json/write-str m))))

(defn <-pgobject
  "Postgres JSONB PGobject → Clojure map."
  [^PGobject pg]
  (when pg
    (json/read-str (.getValue pg) :key-fn keyword)))

(defn <-timestamp
  "Postgres TIMESTAMPTZ → java.time.Instant."
  [^Timestamp ts]
  (when ts
    (.toInstant ts)))

;; ——— Advisory locking ———

(defn advisory-lock!
  "Acquires a transaction-scoped advisory lock keyed by the given name.
   Derives a 64-bit lock key from md5 to minimise accidental collisions."
  [tx lock-name]
  (jdbc/execute-one! tx
                     ["SELECT pg_advisory_xact_lock(
                            ('x' || substr(md5(?), 1, 16))::bit(64)::bigint
                          )"
                      lock-name]))

;; ——— Reading ———

(defn load-stream
  "Returns every event in a stream, ordered by stream-sequence.
   This *is* the event stream for the given aggregate."
  [ds stream-id]
  (let [rows (jdbc/execute!
              ds
              ["SELECT id, global_sequence, stream_id, stream_sequence,
                        event_type, event_version, payload, created_at
                 FROM events
                 WHERE stream_id = ?
                 ORDER BY stream_sequence ASC"
               stream-id]
              {:builder-fn rs/as-unqualified-kebab-maps})]
    (mapv #(-> %
               (update :payload <-pgobject)
               (update :created-at <-timestamp))
          rows)))

;; ——— Writing ———

(def ^:private event-envelope-schema
  [:map
   [:event-type schema/non-empty-string]
   [:payload map?]
   [:event-version {:optional true} pos-int?]])

(defn- invalid-event-envelope!
  [events index event]
  (throw (ex-info "Invalid event envelope"
                  {:error/type :store/invalid-event-envelope
                   :events     events
                   :index      index
                   :event      event
                   :explain    (m/explain event-envelope-schema event)})))

(defn- normalize-events
  "Validates generic event envelope shape and fills default event-version=1.
   Domain-specific payload validation remains in the decider/domain layer."
  [events]
  (mapv (fn [index event]
          (when-not (m/validate event-envelope-schema event)
            (invalid-event-envelope! events index event))
          (update event :event-version #(or % 1)))
        (range)
        events))

(defn- command-type->text [command-type]
  (cond
    (keyword? command-type) (name command-type)
    (string? command-type) command-type
    (nil? command-type) nil
    :else (str command-type)))

(defn- command-payload
  "Returns a stable payload value for idempotency comparisons."
  [command]
  (or (:data command) {}))

(defn- incoming-idempotency-command
  [command]
  {:command-type    (command-type->text (:command-type command))
   :command-payload (command-payload command)})

(defn- idempotency-collision!
  [idempotency-key stream-id incoming-type incoming-payload existing]
  (throw (ex-info "Idempotency key collision"
                  {:error/type       :idempotency/key-collision
                   :error/retryable? false
                   :idempotency-key  idempotency-key
                   :incoming         {:stream-id       stream-id
                                      :command-type    incoming-type
                                      :command-payload incoming-payload}
                   :existing         existing})))

(defn- load-idempotency-record
  [conn idempotency-key]
  (some-> (jdbc/execute-one! conn
                             ["SELECT stream_id, command_type, command_payload
                                 FROM idempotency_keys
                                WHERE idempotency_key = ?"
                              idempotency-key]
                             {:builder-fn rs/as-unqualified-kebab-maps})
          (update :command-payload <-pgobject)))

(defn- same-idempotency-command?
  [conn idempotency-key stream-id {:keys [command-type command-payload]}]
  (let [comparison
        (jdbc/execute-one! conn
                           ["SELECT
                                stream_id = ? AS same_stream,
                                command_type IS NOT DISTINCT FROM ? AS same_type,
                                command_payload = ? AS same_payload
                              FROM idempotency_keys
                              WHERE idempotency_key = ?"
                            stream-id
                            command-type
                            (->pgobject command-payload)
                            idempotency-key]
                           {:builder-fn rs/as-unqualified-kebab-maps})]
    (and (:same-stream comparison)
         (:same-type comparison)
         (:same-payload comparison))))

(defn- inspect-idempotency-key!
  [conn stream-id idempotency-key {:keys [command-type command-payload] :as incoming}]
  (if-let [existing (load-idempotency-record conn idempotency-key)]
    (if (same-idempotency-command? conn idempotency-key stream-id incoming)
      ::idempotent
      (idempotency-collision! idempotency-key
                              stream-id
                              command-type
                              command-payload
                              existing))
    ::missing))

(defn- idempotency-status
  "Attempts to claim the idempotency key for this command.
   Returns one of:
   • ::no-key      — idempotency disabled for this append
  • ::claimed     — key claimed by this transaction
  • ::idempotent  — key already claimed for the same command"
  [tx stream-id idempotency-key command]
  (if-not idempotency-key
    ::no-key
    (let [{:keys [command-type command-payload] :as incoming}
          (incoming-idempotency-command command)
          claimed?
          (jdbc/execute-one! tx
                             ["INSERT INTO idempotency_keys
                                 (idempotency_key, stream_id, command_type, command_payload)
                               VALUES (?, ?, ?, ?)
                               ON CONFLICT (idempotency_key) DO NOTHING
                               RETURNING idempotency_key"
                              idempotency-key
                              stream-id
                              command-type
                              (->pgobject command-payload)])]
      (if claimed?
        ::claimed
        (inspect-idempotency-key! tx stream-id idempotency-key incoming)))))

(defn check-idempotency!
  "Checks whether an idempotency key is already claimed for this command.
   Returns one of:
   • :new        — no key record exists
   • :idempotent — key exists for the same command
   Throws ex-info on key collision (same key, different command)."
  [ds stream-id idempotency-key command]
  (if-not idempotency-key
    :new
    (case (inspect-idempotency-key! ds
                                    stream-id
                                    idempotency-key
                                    (incoming-idempotency-command command))
      ::missing :new
      ::idempotent :idempotent)))

(defn optimistic-concurrency-conflict?
  "Returns true when an exception marks a retryable optimistic conflict."
  [e]
  (let [data (ex-data e)]
    (and (= :concurrency/optimistic-conflict (:error/type data))
         (true? (:error/retryable? data)))))

(defn append-events!
  "Appends events to a stream, enforcing optimistic concurrency and
   command idempotency. Requires explicit command metadata.
   Returns :ok or :idempotent.
   Throws ex-info on concurrency conflict or idempotency collision.

   Race-condition analysis
   ───────────────────────
   • Idempotency is claimed first in idempotency_keys, so concurrent
     reuse of the same key is deterministic.
   • The advisory lock serialises all writers for a given stream-id
     within Postgres, so the version-check + insert is atomic.
   • UNIQUE(stream_id, stream_sequence) remains the safety-net."
  [ds stream-id expected-version idempotency-key command events
   & {:keys [on-events-appended]}]
  (when-not (map? command)
    (throw (ex-info "append-events! requires command metadata map"
                    {:stream-id       stream-id
                     :idempotency-key idempotency-key
                     :command         command})))
  (jdbc/with-transaction [tx ds]
      ;; 1. Claim idempotency key globally (if provided).
    (let [idem-status (idempotency-status tx stream-id idempotency-key command)]
      (if (= ::idempotent idem-status)
        :idempotent
        (let [events (normalize-events events)]
            ;; 2. Acquire a transaction-scoped advisory lock for this stream.
          (advisory-lock! tx (str "stream:" stream-id))

            ;; 3. Optimistic concurrency — stale read detection.
          (let [actual-version
                (or (-> (jdbc/execute-one! tx
                                           ["SELECT MAX(stream_sequence) AS stream_sequence
                        FROM events
                        WHERE stream_id = ?"
                                            stream-id]
                                           {:builder-fn rs/as-unqualified-kebab-maps})
                        :stream-sequence)
                    0)]

            (when (not= actual-version expected-version)
              (throw (ex-info "Optimistic concurrency conflict"
                              {:error/type       :concurrency/optimistic-conflict
                               :error/retryable? true
                               :stream-id        stream-id
                               :expected-version expected-version
                               :actual-version   actual-version})))

              ;; 4. Append domain events.
              ;;    id is a UUIDv7 (application-generated, time-ordered).
              ;;    global_sequence is DB-assigned via BIGSERIAL.
            (doseq [[i event] (map-indexed vector events)]
              (jdbc/execute-one! tx
                                 ["INSERT INTO events
                    (id, stream_id, stream_sequence, event_type, event_version, payload)
                  VALUES (?, ?, ?, ?, ?, ?)"
                                  (uuid-v7)
                                  stream-id
                                  (+ expected-version i 1)
                                  (:event-type event)
                                  (:event-version event)
                                  (->pgobject (:payload event))]))

              ;; 5. Optional post-append hook (e.g. outbox writes).
              ;;    Called within the same transaction.
            (when on-events-appended
              (let [sequences
                    (mapv :global-sequence
                          (jdbc/execute! tx
                                         ["SELECT global_sequence FROM events
                            WHERE stream_id = ? AND stream_sequence > ?
                            ORDER BY stream_sequence ASC"
                                          stream-id expected-version]
                                         {:builder-fn rs/as-unqualified-kebab-maps}))]
                (on-events-appended tx sequences)))

            :ok))))))
