DROP TABLE IF EXISTS event_outbox;
--;;
DROP TABLE IF EXISTS transfer_status;
--;;
DROP TABLE IF EXISTS projection_checkpoints;
--;;
DROP TABLE IF EXISTS account_balances;
--;;
DROP TABLE IF EXISTS idempotency_keys;
--;;
DROP TABLE IF EXISTS events;
